FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app
RUN pip install --upgrade pip

COPY requirements-dashboard.txt .
RUN pip install -r requirements-dashboard.txt

COPY src/dashboard.py src/
COPY .streamlit/ .streamlit/

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "src/dashboard.py", "--server.address=0.0.0.0", "--server.port=8501"]